/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ParentRouteRouteImport } from './routes/parent/route'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as TeacherRouteRouteImport } from './routes/teacher/route'
import { Route as AuthCheckEmailRouteImport } from './routes/_auth/check-email'
import { Route as AuthFirstSignInRouteImport } from './routes/_auth/first-sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSessionExpiredRouteImport } from './routes/_auth/session-expired'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignedInRouteImport } from './routes/_auth/signed-in'
import { Route as AuthWrongPortalRouteImport } from './routes/_auth/wrong-portal'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminApplicantsRouteImport } from './routes/admin/applicants'
import { Route as AdminArmsRouteImport } from './routes/admin/arms'
import { Route as AdminAttReportRouteImport } from './routes/admin/att-report'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminClassSheetRouteImport } from './routes/admin/class-sheet'
import { Route as AdminClassesRouteImport } from './routes/admin/classes'
import { Route as AdminFeesRouteImport } from './routes/admin/fees'
import { Route as AdminInvoicesRouteImport } from './routes/admin/invoices'
import { Route as AdminLibraryRouteImport } from './routes/admin/library'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminNoticesRouteImport } from './routes/admin/notices'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminParentsRouteImport } from './routes/admin/parents'
import { Route as AdminParentsInvitedRouteImport } from './routes/admin/parents-invited'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminResultQueueRouteImport } from './routes/admin/result-queue'
import { Route as AdminResultsRouteImport } from './routes/admin/results'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSpendingsRouteImport } from './routes/admin/spendings'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminStaffAdminRouteImport } from './routes/admin/staff-admin'
import { Route as AdminStaffOtherRouteImport } from './routes/admin/staff-other'
import { Route as AdminStaffTeachersRouteImport } from './routes/admin/staff-teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminSubjectsRouteImport } from './routes/admin/subjects'
import { Route as AdminTermsRouteImport } from './routes/admin/terms'
import { Route as AdminTimetableRouteImport } from './routes/admin/timetable'
import { Route as ParentIndexRouteImport } from './routes/parent/index'
import { Route as ParentAssignmentsRouteImport } from './routes/parent/assignments'
import { Route as ParentAttendanceRouteImport } from './routes/parent/attendance'
import { Route as ParentInvoicesRouteImport } from './routes/parent/invoices'
import { Route as ParentMsgSchoolRouteImport } from './routes/parent/msg-school'
import { Route as ParentNotificationsRouteImport } from './routes/parent/notifications'
import { Route as ParentProfileRouteImport } from './routes/parent/profile'
import { Route as ParentResultsRouteImport } from './routes/parent/results'
import { Route as ParentTimetableRouteImport } from './routes/parent/timetable'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentAttendanceRouteImport } from './routes/student/attendance'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentInvoicesRouteImport } from './routes/student/invoices'
import { Route as StudentNotificationsRouteImport } from './routes/student/notifications'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentResultsRouteImport } from './routes/student/results'
import { Route as StudentTimetableRouteImport } from './routes/student/timetable'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher/assignments'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher/attendance'
import { Route as TeacherEclassesRouteImport } from './routes/teacher/eclasses'
import { Route as TeacherMsgAdminRouteImport } from './routes/teacher/msg-admin'
import { Route as TeacherMsgStudentsRouteImport } from './routes/teacher/msg-students'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher/notifications'
import { Route as TeacherProfileRouteImport } from './routes/teacher/profile'
import { Route as TeacherQuestionsRouteImport } from './routes/teacher/questions'
import { Route as TeacherRegistersRouteImport } from './routes/teacher/registers'
import { Route as TeacherResultsRouteImport } from './routes/teacher/results'
import { Route as TeacherScoresRouteImport } from './routes/teacher/scores'
import { Route as TeacherStudentsRouteImport } from './routes/teacher/students'
import { Route as TeacherSubjectsRouteImport } from './routes/teacher/subjects'
import { Route as TeacherSubmissionsRouteImport } from './routes/teacher/submissions'
import { Route as TeacherTimetableRouteImport } from './routes/teacher/timetable'
import { Route as TeacherTopicsRouteImport } from './routes/teacher/topics'
import { Route as AdminCollectionActionRouteImport } from './routes/admin/$collection.action'
import { Route as AdminCollectionNewRouteImport } from './routes/admin/$collection.new'
import { Route as AdminCollectIndexRouteImport } from './routes/admin/collect.index'
import { Route as AdminCollectPupilRouteImport } from './routes/admin/collect.pupil'
import { Route as AdminCollectReportRouteImport } from './routes/admin/collect.report'
import { Route as ParentCollectionRecordIdRouteImport } from './routes/parent/$collection.$recordId'
import { Route as ParentChildrenIndexRouteImport } from './routes/parent/children.index'
import { Route as ParentChildrenAddRouteImport } from './routes/parent/children.add'
import { Route as ParentPayIndexRouteImport } from './routes/parent/pay.index'
import { Route as ParentPayDoneRouteImport } from './routes/parent/pay.done'
import { Route as StudentCollectionRecordIdRouteImport } from './routes/student/$collection.$recordId'
import { Route as StudentAssignmentsIndexRouteImport } from './routes/student/assignments.index'
import { Route as StudentMaterialsIndexRouteImport } from './routes/student/materials.index'
import { Route as TeacherCollectionNewRouteImport } from './routes/teacher/$collection.new'
import { Route as TeacherUploadsIndexRouteImport } from './routes/teacher/uploads.index'
import { Route as AdminCollectionRecordIdIndexRouteImport } from './routes/admin/$collection.$recordId.index'
import { Route as AdminCollectionRecordIdEditRouteImport } from './routes/admin/$collection.$recordId.edit'
import { Route as AdminCollectReceiptInvoiceIdRouteImport } from './routes/admin/collect.receipt.$invoiceId'
import { Route as StudentAssignmentsAssignmentIdIndexRouteImport } from './routes/student/assignments.$assignmentId.index'
import { Route as StudentAssignmentsAssignmentIdResultRouteImport } from './routes/student/assignments.$assignmentId.result'
import { Route as TeacherCollectionRecordIdIndexRouteImport } from './routes/teacher/$collection.$recordId.index'
import { Route as TeacherCollectionRecordIdEditRouteImport } from './routes/teacher/$collection.$recordId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRouteRoute = ParentRouteRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRouteRoute = TeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFirstSignInRoute = AuthFirstSignInRouteImport.update({
  id: '/first-sign-in',
  path: '/first-sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionExpiredRoute = AuthSessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignedInRoute = AuthSignedInRouteImport.update({
  id: '/signed-in',
  path: '/signed-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWrongPortalRoute = AuthWrongPortalRouteImport.update({
  id: '/wrong-portal',
  path: '/wrong-portal',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicantsRoute = AdminApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArmsRoute = AdminArmsRouteImport.update({
  id: '/arms',
  path: '/arms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttReportRoute = AdminAttReportRouteImport.update({
  id: '/att-report',
  path: '/att-report',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClassSheetRoute = AdminClassSheetRouteImport.update({
  id: '/class-sheet',
  path: '/class-sheet',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminParentsRoute = AdminParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminParentsInvitedRoute = AdminParentsInvitedRouteImport.update({
  id: '/parents-invited',
  path: '/parents-invited',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResultQueueRoute = AdminResultQueueRouteImport.update({
  id: '/result-queue',
  path: '/result-queue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSpendingsRoute = AdminSpendingsRouteImport.update({
  id: '/spendings',
  path: '/spendings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffAdminRoute = AdminStaffAdminRouteImport.update({
  id: '/staff-admin',
  path: '/staff-admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffOtherRoute = AdminStaffOtherRouteImport.update({
  id: '/staff-other',
  path: '/staff-other',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffTeachersRoute = AdminStaffTeachersRouteImport.update({
  id: '/staff-teachers',
  path: '/staff-teachers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTermsRoute = AdminTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentAssignmentsRoute = ParentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentAttendanceRoute = ParentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentInvoicesRoute = ParentInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentMsgSchoolRoute = ParentMsgSchoolRouteImport.update({
  id: '/msg-school',
  path: '/msg-school',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentProfileRoute = ParentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentResultsRoute = ParentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentTimetableRoute = ParentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => ParentRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentInvoicesRoute = StudentInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRouteRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherEclassesRoute = TeacherEclassesRouteImport.update({
  id: '/eclasses',
  path: '/eclasses',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherMsgAdminRoute = TeacherMsgAdminRouteImport.update({
  id: '/msg-admin',
  path: '/msg-admin',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherMsgStudentsRoute = TeacherMsgStudentsRouteImport.update({
  id: '/msg-students',
  path: '/msg-students',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherQuestionsRoute = TeacherQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherRegistersRoute = TeacherRegistersRouteImport.update({
  id: '/registers',
  path: '/registers',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherResultsRoute = TeacherResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherScoresRoute = TeacherScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherSubjectsRoute = TeacherSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherSubmissionsRoute = TeacherSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherTopicsRoute = TeacherTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const AdminCollectionActionRoute = AdminCollectionActionRouteImport.update({
  id: '/$collection/action',
  path: '/$collection/action',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectionNewRoute = AdminCollectionNewRouteImport.update({
  id: '/$collection/new',
  path: '/$collection/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectIndexRoute = AdminCollectIndexRouteImport.update({
  id: '/collect/',
  path: '/collect/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectPupilRoute = AdminCollectPupilRouteImport.update({
  id: '/collect/pupil',
  path: '/collect/pupil',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectReportRoute = AdminCollectReportRouteImport.update({
  id: '/collect/report',
  path: '/collect/report',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ParentCollectionRecordIdRoute =
  ParentCollectionRecordIdRouteImport.update({
    id: '/$collection/$recordId',
    path: '/$collection/$recordId',
    getParentRoute: () => ParentRouteRoute,
  } as any)
const ParentChildrenIndexRoute = ParentChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentChildrenAddRoute = ParentChildrenAddRouteImport.update({
  id: '/children/add',
  path: '/children/add',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentPayIndexRoute = ParentPayIndexRouteImport.update({
  id: '/pay/',
  path: '/pay/',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentPayDoneRoute = ParentPayDoneRouteImport.update({
  id: '/pay/done',
  path: '/pay/done',
  getParentRoute: () => ParentRouteRoute,
} as any)
const StudentCollectionRecordIdRoute =
  StudentCollectionRecordIdRouteImport.update({
    id: '/$collection/$recordId',
    path: '/$collection/$recordId',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentAssignmentsIndexRoute = StudentAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMaterialsIndexRoute = StudentMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const TeacherCollectionNewRoute = TeacherCollectionNewRouteImport.update({
  id: '/$collection/new',
  path: '/$collection/new',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherUploadsIndexRoute = TeacherUploadsIndexRouteImport.update({
  id: '/uploads/',
  path: '/uploads/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const AdminCollectionRecordIdIndexRoute =
  AdminCollectionRecordIdIndexRouteImport.update({
    id: '/$collection/$recordId/',
    path: '/$collection/$recordId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCollectionRecordIdEditRoute =
  AdminCollectionRecordIdEditRouteImport.update({
    id: '/$collection/$recordId/edit',
    path: '/$collection/$recordId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCollectReceiptInvoiceIdRoute =
  AdminCollectReceiptInvoiceIdRouteImport.update({
    id: '/collect/receipt/$invoiceId',
    path: '/collect/receipt/$invoiceId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const StudentAssignmentsAssignmentIdIndexRoute =
  StudentAssignmentsAssignmentIdIndexRouteImport.update({
    id: '/assignments/$assignmentId/',
    path: '/assignments/$assignmentId/',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentAssignmentsAssignmentIdResultRoute =
  StudentAssignmentsAssignmentIdResultRouteImport.update({
    id: '/assignments/$assignmentId/result',
    path: '/assignments/$assignmentId/result',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const TeacherCollectionRecordIdIndexRoute =
  TeacherCollectionRecordIdIndexRouteImport.update({
    id: '/$collection/$recordId/',
    path: '/$collection/$recordId/',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const TeacherCollectionRecordIdEditRoute =
  TeacherCollectionRecordIdEditRouteImport.update({
    id: '/$collection/$recordId/edit',
    path: '/$collection/$recordId/edit',
    getParentRoute: () => TeacherRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/parent': typeof ParentRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/check-email': typeof AuthCheckEmailRoute
  '/first-sign-in': typeof AuthFirstSignInRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/session-expired': typeof AuthSessionExpiredRoute
  '/sign-in': typeof AuthSignInRoute
  '/signed-in': typeof AuthSignedInRoute
  '/wrong-portal': typeof AuthWrongPortalRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/arms': typeof AdminArmsRoute
  '/admin/att-report': typeof AdminAttReportRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/class-sheet': typeof AdminClassSheetRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/parents-invited': typeof AdminParentsInvitedRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/result-queue': typeof AdminResultQueueRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/spendings': typeof AdminSpendingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/staff-admin': typeof AdminStaffAdminRoute
  '/admin/staff-other': typeof AdminStaffOtherRoute
  '/admin/staff-teachers': typeof AdminStaffTeachersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/terms': typeof AdminTermsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/parent/assignments': typeof ParentAssignmentsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/invoices': typeof ParentInvoicesRoute
  '/parent/msg-school': typeof ParentMsgSchoolRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/profile': typeof ParentProfileRoute
  '/parent/results': typeof ParentResultsRoute
  '/parent/timetable': typeof ParentTimetableRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/invoices': typeof StudentInvoicesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/eclasses': typeof TeacherEclassesRoute
  '/teacher/msg-admin': typeof TeacherMsgAdminRoute
  '/teacher/msg-students': typeof TeacherMsgStudentsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/questions': typeof TeacherQuestionsRoute
  '/teacher/registers': typeof TeacherRegistersRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/scores': typeof TeacherScoresRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/teacher/topics': typeof TeacherTopicsRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/$collection/action': typeof AdminCollectionActionRoute
  '/admin/$collection/new': typeof AdminCollectionNewRoute
  '/admin/collect/pupil': typeof AdminCollectPupilRoute
  '/admin/collect/report': typeof AdminCollectReportRoute
  '/parent/$collection/$recordId': typeof ParentCollectionRecordIdRoute
  '/parent/children/add': typeof ParentChildrenAddRoute
  '/parent/pay/done': typeof ParentPayDoneRoute
  '/student/$collection/$recordId': typeof StudentCollectionRecordIdRoute
  '/teacher/$collection/new': typeof TeacherCollectionNewRoute
  '/admin/collect/': typeof AdminCollectIndexRoute
  '/parent/children/': typeof ParentChildrenIndexRoute
  '/parent/pay/': typeof ParentPayIndexRoute
  '/student/assignments/': typeof StudentAssignmentsIndexRoute
  '/student/materials/': typeof StudentMaterialsIndexRoute
  '/teacher/uploads/': typeof TeacherUploadsIndexRoute
  '/admin/$collection/$recordId/edit': typeof AdminCollectionRecordIdEditRoute
  '/admin/collect/receipt/$invoiceId': typeof AdminCollectReceiptInvoiceIdRoute
  '/student/assignments/$assignmentId/result': typeof StudentAssignmentsAssignmentIdResultRoute
  '/teacher/$collection/$recordId/edit': typeof TeacherCollectionRecordIdEditRoute
  '/admin/$collection/$recordId/': typeof AdminCollectionRecordIdIndexRoute
  '/student/assignments/$assignmentId/': typeof StudentAssignmentsAssignmentIdIndexRoute
  '/teacher/$collection/$recordId/': typeof TeacherCollectionRecordIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/first-sign-in': typeof AuthFirstSignInRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/session-expired': typeof AuthSessionExpiredRoute
  '/sign-in': typeof AuthSignInRoute
  '/signed-in': typeof AuthSignedInRoute
  '/wrong-portal': typeof AuthWrongPortalRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/arms': typeof AdminArmsRoute
  '/admin/att-report': typeof AdminAttReportRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/class-sheet': typeof AdminClassSheetRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/parents-invited': typeof AdminParentsInvitedRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/result-queue': typeof AdminResultQueueRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/spendings': typeof AdminSpendingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/staff-admin': typeof AdminStaffAdminRoute
  '/admin/staff-other': typeof AdminStaffOtherRoute
  '/admin/staff-teachers': typeof AdminStaffTeachersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/terms': typeof AdminTermsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/parent/assignments': typeof ParentAssignmentsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/invoices': typeof ParentInvoicesRoute
  '/parent/msg-school': typeof ParentMsgSchoolRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/profile': typeof ParentProfileRoute
  '/parent/results': typeof ParentResultsRoute
  '/parent/timetable': typeof ParentTimetableRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/invoices': typeof StudentInvoicesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/eclasses': typeof TeacherEclassesRoute
  '/teacher/msg-admin': typeof TeacherMsgAdminRoute
  '/teacher/msg-students': typeof TeacherMsgStudentsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/questions': typeof TeacherQuestionsRoute
  '/teacher/registers': typeof TeacherRegistersRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/scores': typeof TeacherScoresRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/teacher/topics': typeof TeacherTopicsRoute
  '/admin': typeof AdminIndexRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/$collection/action': typeof AdminCollectionActionRoute
  '/admin/$collection/new': typeof AdminCollectionNewRoute
  '/admin/collect/pupil': typeof AdminCollectPupilRoute
  '/admin/collect/report': typeof AdminCollectReportRoute
  '/parent/$collection/$recordId': typeof ParentCollectionRecordIdRoute
  '/parent/children/add': typeof ParentChildrenAddRoute
  '/parent/pay/done': typeof ParentPayDoneRoute
  '/student/$collection/$recordId': typeof StudentCollectionRecordIdRoute
  '/teacher/$collection/new': typeof TeacherCollectionNewRoute
  '/admin/collect': typeof AdminCollectIndexRoute
  '/parent/children': typeof ParentChildrenIndexRoute
  '/parent/pay': typeof ParentPayIndexRoute
  '/student/assignments': typeof StudentAssignmentsIndexRoute
  '/student/materials': typeof StudentMaterialsIndexRoute
  '/teacher/uploads': typeof TeacherUploadsIndexRoute
  '/admin/$collection/$recordId/edit': typeof AdminCollectionRecordIdEditRoute
  '/admin/collect/receipt/$invoiceId': typeof AdminCollectReceiptInvoiceIdRoute
  '/student/assignments/$assignmentId/result': typeof StudentAssignmentsAssignmentIdResultRoute
  '/teacher/$collection/$recordId/edit': typeof TeacherCollectionRecordIdEditRoute
  '/admin/$collection/$recordId': typeof AdminCollectionRecordIdIndexRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdIndexRoute
  '/teacher/$collection/$recordId': typeof TeacherCollectionRecordIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/parent': typeof ParentRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/check-email': typeof AuthCheckEmailRoute
  '/_auth/first-sign-in': typeof AuthFirstSignInRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/session-expired': typeof AuthSessionExpiredRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/signed-in': typeof AuthSignedInRoute
  '/_auth/wrong-portal': typeof AuthWrongPortalRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/arms': typeof AdminArmsRoute
  '/admin/att-report': typeof AdminAttReportRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/class-sheet': typeof AdminClassSheetRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/parents-invited': typeof AdminParentsInvitedRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/result-queue': typeof AdminResultQueueRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/spendings': typeof AdminSpendingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/staff-admin': typeof AdminStaffAdminRoute
  '/admin/staff-other': typeof AdminStaffOtherRoute
  '/admin/staff-teachers': typeof AdminStaffTeachersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/terms': typeof AdminTermsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/parent/assignments': typeof ParentAssignmentsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/invoices': typeof ParentInvoicesRoute
  '/parent/msg-school': typeof ParentMsgSchoolRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/profile': typeof ParentProfileRoute
  '/parent/results': typeof ParentResultsRoute
  '/parent/timetable': typeof ParentTimetableRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/invoices': typeof StudentInvoicesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/eclasses': typeof TeacherEclassesRoute
  '/teacher/msg-admin': typeof TeacherMsgAdminRoute
  '/teacher/msg-students': typeof TeacherMsgStudentsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/questions': typeof TeacherQuestionsRoute
  '/teacher/registers': typeof TeacherRegistersRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/scores': typeof TeacherScoresRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/teacher/topics': typeof TeacherTopicsRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/$collection/action': typeof AdminCollectionActionRoute
  '/admin/$collection/new': typeof AdminCollectionNewRoute
  '/admin/collect/pupil': typeof AdminCollectPupilRoute
  '/admin/collect/report': typeof AdminCollectReportRoute
  '/parent/$collection/$recordId': typeof ParentCollectionRecordIdRoute
  '/parent/children/add': typeof ParentChildrenAddRoute
  '/parent/pay/done': typeof ParentPayDoneRoute
  '/student/$collection/$recordId': typeof StudentCollectionRecordIdRoute
  '/teacher/$collection/new': typeof TeacherCollectionNewRoute
  '/admin/collect/': typeof AdminCollectIndexRoute
  '/parent/children/': typeof ParentChildrenIndexRoute
  '/parent/pay/': typeof ParentPayIndexRoute
  '/student/assignments/': typeof StudentAssignmentsIndexRoute
  '/student/materials/': typeof StudentMaterialsIndexRoute
  '/teacher/uploads/': typeof TeacherUploadsIndexRoute
  '/admin/$collection/$recordId/edit': typeof AdminCollectionRecordIdEditRoute
  '/admin/collect/receipt/$invoiceId': typeof AdminCollectReceiptInvoiceIdRoute
  '/student/assignments/$assignmentId/result': typeof StudentAssignmentsAssignmentIdResultRoute
  '/teacher/$collection/$recordId/edit': typeof TeacherCollectionRecordIdEditRoute
  '/admin/$collection/$recordId/': typeof AdminCollectionRecordIdIndexRoute
  '/student/assignments/$assignmentId/': typeof StudentAssignmentsAssignmentIdIndexRoute
  '/teacher/$collection/$recordId/': typeof TeacherCollectionRecordIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/check-email'
    | '/first-sign-in'
    | '/forgot-password'
    | '/reset-password'
    | '/session-expired'
    | '/sign-in'
    | '/signed-in'
    | '/wrong-portal'
    | '/admin/analytics'
    | '/admin/applicants'
    | '/admin/arms'
    | '/admin/att-report'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/class-sheet'
    | '/admin/classes'
    | '/admin/fees'
    | '/admin/invoices'
    | '/admin/library'
    | '/admin/logs'
    | '/admin/notices'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/parents-invited'
    | '/admin/profile'
    | '/admin/result-queue'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/spendings'
    | '/admin/staff'
    | '/admin/staff-admin'
    | '/admin/staff-other'
    | '/admin/staff-teachers'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/terms'
    | '/admin/timetable'
    | '/parent/assignments'
    | '/parent/attendance'
    | '/parent/invoices'
    | '/parent/msg-school'
    | '/parent/notifications'
    | '/parent/profile'
    | '/parent/results'
    | '/parent/timetable'
    | '/student/attendance'
    | '/student/courses'
    | '/student/invoices'
    | '/student/notifications'
    | '/student/profile'
    | '/student/results'
    | '/student/timetable'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/eclasses'
    | '/teacher/msg-admin'
    | '/teacher/msg-students'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/questions'
    | '/teacher/registers'
    | '/teacher/results'
    | '/teacher/scores'
    | '/teacher/students'
    | '/teacher/subjects'
    | '/teacher/submissions'
    | '/teacher/timetable'
    | '/teacher/topics'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/admin/$collection/action'
    | '/admin/$collection/new'
    | '/admin/collect/pupil'
    | '/admin/collect/report'
    | '/parent/$collection/$recordId'
    | '/parent/children/add'
    | '/parent/pay/done'
    | '/student/$collection/$recordId'
    | '/teacher/$collection/new'
    | '/admin/collect/'
    | '/parent/children/'
    | '/parent/pay/'
    | '/student/assignments/'
    | '/student/materials/'
    | '/teacher/uploads/'
    | '/admin/$collection/$recordId/edit'
    | '/admin/collect/receipt/$invoiceId'
    | '/student/assignments/$assignmentId/result'
    | '/teacher/$collection/$recordId/edit'
    | '/admin/$collection/$recordId/'
    | '/student/assignments/$assignmentId/'
    | '/teacher/$collection/$recordId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/first-sign-in'
    | '/forgot-password'
    | '/reset-password'
    | '/session-expired'
    | '/sign-in'
    | '/signed-in'
    | '/wrong-portal'
    | '/admin/analytics'
    | '/admin/applicants'
    | '/admin/arms'
    | '/admin/att-report'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/class-sheet'
    | '/admin/classes'
    | '/admin/fees'
    | '/admin/invoices'
    | '/admin/library'
    | '/admin/logs'
    | '/admin/notices'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/parents-invited'
    | '/admin/profile'
    | '/admin/result-queue'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/spendings'
    | '/admin/staff'
    | '/admin/staff-admin'
    | '/admin/staff-other'
    | '/admin/staff-teachers'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/terms'
    | '/admin/timetable'
    | '/parent/assignments'
    | '/parent/attendance'
    | '/parent/invoices'
    | '/parent/msg-school'
    | '/parent/notifications'
    | '/parent/profile'
    | '/parent/results'
    | '/parent/timetable'
    | '/student/attendance'
    | '/student/courses'
    | '/student/invoices'
    | '/student/notifications'
    | '/student/profile'
    | '/student/results'
    | '/student/timetable'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/eclasses'
    | '/teacher/msg-admin'
    | '/teacher/msg-students'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/questions'
    | '/teacher/registers'
    | '/teacher/results'
    | '/teacher/scores'
    | '/teacher/students'
    | '/teacher/subjects'
    | '/teacher/submissions'
    | '/teacher/timetable'
    | '/teacher/topics'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/admin/$collection/action'
    | '/admin/$collection/new'
    | '/admin/collect/pupil'
    | '/admin/collect/report'
    | '/parent/$collection/$recordId'
    | '/parent/children/add'
    | '/parent/pay/done'
    | '/student/$collection/$recordId'
    | '/teacher/$collection/new'
    | '/admin/collect'
    | '/parent/children'
    | '/parent/pay'
    | '/student/assignments'
    | '/student/materials'
    | '/teacher/uploads'
    | '/admin/$collection/$recordId/edit'
    | '/admin/collect/receipt/$invoiceId'
    | '/student/assignments/$assignmentId/result'
    | '/teacher/$collection/$recordId/edit'
    | '/admin/$collection/$recordId'
    | '/student/assignments/$assignmentId'
    | '/teacher/$collection/$recordId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/_auth'
    | '/_auth/check-email'
    | '/_auth/first-sign-in'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/session-expired'
    | '/_auth/sign-in'
    | '/_auth/signed-in'
    | '/_auth/wrong-portal'
    | '/admin/analytics'
    | '/admin/applicants'
    | '/admin/arms'
    | '/admin/att-report'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/class-sheet'
    | '/admin/classes'
    | '/admin/fees'
    | '/admin/invoices'
    | '/admin/library'
    | '/admin/logs'
    | '/admin/notices'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/parents-invited'
    | '/admin/profile'
    | '/admin/result-queue'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/spendings'
    | '/admin/staff'
    | '/admin/staff-admin'
    | '/admin/staff-other'
    | '/admin/staff-teachers'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/terms'
    | '/admin/timetable'
    | '/parent/assignments'
    | '/parent/attendance'
    | '/parent/invoices'
    | '/parent/msg-school'
    | '/parent/notifications'
    | '/parent/profile'
    | '/parent/results'
    | '/parent/timetable'
    | '/student/attendance'
    | '/student/courses'
    | '/student/invoices'
    | '/student/notifications'
    | '/student/profile'
    | '/student/results'
    | '/student/timetable'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/eclasses'
    | '/teacher/msg-admin'
    | '/teacher/msg-students'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/questions'
    | '/teacher/registers'
    | '/teacher/results'
    | '/teacher/scores'
    | '/teacher/students'
    | '/teacher/subjects'
    | '/teacher/submissions'
    | '/teacher/timetable'
    | '/teacher/topics'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/admin/$collection/action'
    | '/admin/$collection/new'
    | '/admin/collect/pupil'
    | '/admin/collect/report'
    | '/parent/$collection/$recordId'
    | '/parent/children/add'
    | '/parent/pay/done'
    | '/student/$collection/$recordId'
    | '/teacher/$collection/new'
    | '/admin/collect/'
    | '/parent/children/'
    | '/parent/pay/'
    | '/student/assignments/'
    | '/student/materials/'
    | '/teacher/uploads/'
    | '/admin/$collection/$recordId/edit'
    | '/admin/collect/receipt/$invoiceId'
    | '/student/assignments/$assignmentId/result'
    | '/teacher/$collection/$recordId/edit'
    | '/admin/$collection/$recordId/'
    | '/student/assignments/$assignmentId/'
    | '/teacher/$collection/$recordId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ParentRouteRoute: typeof ParentRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  TeacherRouteRoute: typeof TeacherRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/check-email': {
      id: '/_auth/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/first-sign-in': {
      id: '/_auth/first-sign-in'
      path: '/first-sign-in'
      fullPath: '/first-sign-in'
      preLoaderRoute: typeof AuthFirstSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/session-expired': {
      id: '/_auth/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof AuthSessionExpiredRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signed-in': {
      id: '/_auth/signed-in'
      path: '/signed-in'
      fullPath: '/signed-in'
      preLoaderRoute: typeof AuthSignedInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/wrong-portal': {
      id: '/_auth/wrong-portal'
      path: '/wrong-portal'
      fullPath: '/wrong-portal'
      preLoaderRoute: typeof AuthWrongPortalRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applicants': {
      id: '/admin/applicants'
      path: '/applicants'
      fullPath: '/admin/applicants'
      preLoaderRoute: typeof AdminApplicantsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/arms': {
      id: '/admin/arms'
      path: '/arms'
      fullPath: '/admin/arms'
      preLoaderRoute: typeof AdminArmsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/att-report': {
      id: '/admin/att-report'
      path: '/att-report'
      fullPath: '/admin/att-report'
      preLoaderRoute: typeof AdminAttReportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/class-sheet': {
      id: '/admin/class-sheet'
      path: '/class-sheet'
      fullPath: '/admin/class-sheet'
      preLoaderRoute: typeof AdminClassSheetRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/parents': {
      id: '/admin/parents'
      path: '/parents'
      fullPath: '/admin/parents'
      preLoaderRoute: typeof AdminParentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/parents-invited': {
      id: '/admin/parents-invited'
      path: '/parents-invited'
      fullPath: '/admin/parents-invited'
      preLoaderRoute: typeof AdminParentsInvitedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/result-queue': {
      id: '/admin/result-queue'
      path: '/result-queue'
      fullPath: '/admin/result-queue'
      preLoaderRoute: typeof AdminResultQueueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/spendings': {
      id: '/admin/spendings'
      path: '/spendings'
      fullPath: '/admin/spendings'
      preLoaderRoute: typeof AdminSpendingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff-admin': {
      id: '/admin/staff-admin'
      path: '/staff-admin'
      fullPath: '/admin/staff-admin'
      preLoaderRoute: typeof AdminStaffAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff-other': {
      id: '/admin/staff-other'
      path: '/staff-other'
      fullPath: '/admin/staff-other'
      preLoaderRoute: typeof AdminStaffOtherRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff-teachers': {
      id: '/admin/staff-teachers'
      path: '/staff-teachers'
      fullPath: '/admin/staff-teachers'
      preLoaderRoute: typeof AdminStaffTeachersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/terms': {
      id: '/admin/terms'
      path: '/terms'
      fullPath: '/admin/terms'
      preLoaderRoute: typeof AdminTermsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/assignments': {
      id: '/parent/assignments'
      path: '/assignments'
      fullPath: '/parent/assignments'
      preLoaderRoute: typeof ParentAssignmentsRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/attendance': {
      id: '/parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof ParentAttendanceRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/invoices': {
      id: '/parent/invoices'
      path: '/invoices'
      fullPath: '/parent/invoices'
      preLoaderRoute: typeof ParentInvoicesRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/msg-school': {
      id: '/parent/msg-school'
      path: '/msg-school'
      fullPath: '/parent/msg-school'
      preLoaderRoute: typeof ParentMsgSchoolRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/profile': {
      id: '/parent/profile'
      path: '/profile'
      fullPath: '/parent/profile'
      preLoaderRoute: typeof ParentProfileRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/results': {
      id: '/parent/results'
      path: '/results'
      fullPath: '/parent/results'
      preLoaderRoute: typeof ParentResultsRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/timetable': {
      id: '/parent/timetable'
      path: '/timetable'
      fullPath: '/parent/timetable'
      preLoaderRoute: typeof ParentTimetableRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/invoices': {
      id: '/student/invoices'
      path: '/invoices'
      fullPath: '/student/invoices'
      preLoaderRoute: typeof StudentInvoicesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/results': {
      id: '/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/eclasses': {
      id: '/teacher/eclasses'
      path: '/eclasses'
      fullPath: '/teacher/eclasses'
      preLoaderRoute: typeof TeacherEclassesRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/msg-admin': {
      id: '/teacher/msg-admin'
      path: '/msg-admin'
      fullPath: '/teacher/msg-admin'
      preLoaderRoute: typeof TeacherMsgAdminRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/msg-students': {
      id: '/teacher/msg-students'
      path: '/msg-students'
      fullPath: '/teacher/msg-students'
      preLoaderRoute: typeof TeacherMsgStudentsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/questions': {
      id: '/teacher/questions'
      path: '/questions'
      fullPath: '/teacher/questions'
      preLoaderRoute: typeof TeacherQuestionsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/registers': {
      id: '/teacher/registers'
      path: '/registers'
      fullPath: '/teacher/registers'
      preLoaderRoute: typeof TeacherRegistersRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/results': {
      id: '/teacher/results'
      path: '/results'
      fullPath: '/teacher/results'
      preLoaderRoute: typeof TeacherResultsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/scores': {
      id: '/teacher/scores'
      path: '/scores'
      fullPath: '/teacher/scores'
      preLoaderRoute: typeof TeacherScoresRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/subjects': {
      id: '/teacher/subjects'
      path: '/subjects'
      fullPath: '/teacher/subjects'
      preLoaderRoute: typeof TeacherSubjectsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/submissions': {
      id: '/teacher/submissions'
      path: '/submissions'
      fullPath: '/teacher/submissions'
      preLoaderRoute: typeof TeacherSubmissionsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/timetable': {
      id: '/teacher/timetable'
      path: '/timetable'
      fullPath: '/teacher/timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/topics': {
      id: '/teacher/topics'
      path: '/topics'
      fullPath: '/teacher/topics'
      preLoaderRoute: typeof TeacherTopicsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/admin/$collection/action': {
      id: '/admin/$collection/action'
      path: '/$collection/action'
      fullPath: '/admin/$collection/action'
      preLoaderRoute: typeof AdminCollectionActionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$collection/new': {
      id: '/admin/$collection/new'
      path: '/$collection/new'
      fullPath: '/admin/$collection/new'
      preLoaderRoute: typeof AdminCollectionNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collect/': {
      id: '/admin/collect/'
      path: '/collect'
      fullPath: '/admin/collect/'
      preLoaderRoute: typeof AdminCollectIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collect/pupil': {
      id: '/admin/collect/pupil'
      path: '/collect/pupil'
      fullPath: '/admin/collect/pupil'
      preLoaderRoute: typeof AdminCollectPupilRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collect/report': {
      id: '/admin/collect/report'
      path: '/collect/report'
      fullPath: '/admin/collect/report'
      preLoaderRoute: typeof AdminCollectReportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/parent/$collection/$recordId': {
      id: '/parent/$collection/$recordId'
      path: '/$collection/$recordId'
      fullPath: '/parent/$collection/$recordId'
      preLoaderRoute: typeof ParentCollectionRecordIdRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/children/': {
      id: '/parent/children/'
      path: '/children'
      fullPath: '/parent/children/'
      preLoaderRoute: typeof ParentChildrenIndexRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/children/add': {
      id: '/parent/children/add'
      path: '/children/add'
      fullPath: '/parent/children/add'
      preLoaderRoute: typeof ParentChildrenAddRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/pay/': {
      id: '/parent/pay/'
      path: '/pay'
      fullPath: '/parent/pay/'
      preLoaderRoute: typeof ParentPayIndexRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/pay/done': {
      id: '/parent/pay/done'
      path: '/pay/done'
      fullPath: '/parent/pay/done'
      preLoaderRoute: typeof ParentPayDoneRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/student/$collection/$recordId': {
      id: '/student/$collection/$recordId'
      path: '/$collection/$recordId'
      fullPath: '/student/$collection/$recordId'
      preLoaderRoute: typeof StudentCollectionRecordIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/assignments/': {
      id: '/student/assignments/'
      path: '/assignments'
      fullPath: '/student/assignments/'
      preLoaderRoute: typeof StudentAssignmentsIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/materials/': {
      id: '/student/materials/'
      path: '/materials'
      fullPath: '/student/materials/'
      preLoaderRoute: typeof StudentMaterialsIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/$collection/new': {
      id: '/teacher/$collection/new'
      path: '/$collection/new'
      fullPath: '/teacher/$collection/new'
      preLoaderRoute: typeof TeacherCollectionNewRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/uploads/': {
      id: '/teacher/uploads/'
      path: '/uploads'
      fullPath: '/teacher/uploads/'
      preLoaderRoute: typeof TeacherUploadsIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/admin/$collection/$recordId/': {
      id: '/admin/$collection/$recordId/'
      path: '/$collection/$recordId'
      fullPath: '/admin/$collection/$recordId/'
      preLoaderRoute: typeof AdminCollectionRecordIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$collection/$recordId/edit': {
      id: '/admin/$collection/$recordId/edit'
      path: '/$collection/$recordId/edit'
      fullPath: '/admin/$collection/$recordId/edit'
      preLoaderRoute: typeof AdminCollectionRecordIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collect/receipt/$invoiceId': {
      id: '/admin/collect/receipt/$invoiceId'
      path: '/collect/receipt/$invoiceId'
      fullPath: '/admin/collect/receipt/$invoiceId'
      preLoaderRoute: typeof AdminCollectReceiptInvoiceIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/assignments/$assignmentId/': {
      id: '/student/assignments/$assignmentId/'
      path: '/assignments/$assignmentId'
      fullPath: '/student/assignments/$assignmentId/'
      preLoaderRoute: typeof StudentAssignmentsAssignmentIdIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/assignments/$assignmentId/result': {
      id: '/student/assignments/$assignmentId/result'
      path: '/assignments/$assignmentId/result'
      fullPath: '/student/assignments/$assignmentId/result'
      preLoaderRoute: typeof StudentAssignmentsAssignmentIdResultRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/$collection/$recordId/': {
      id: '/teacher/$collection/$recordId/'
      path: '/$collection/$recordId'
      fullPath: '/teacher/$collection/$recordId/'
      preLoaderRoute: typeof TeacherCollectionRecordIdIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/$collection/$recordId/edit': {
      id: '/teacher/$collection/$recordId/edit'
      path: '/$collection/$recordId/edit'
      fullPath: '/teacher/$collection/$recordId/edit'
      preLoaderRoute: typeof TeacherCollectionRecordIdEditRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicantsRoute: typeof AdminApplicantsRoute
  AdminArmsRoute: typeof AdminArmsRoute
  AdminAttReportRoute: typeof AdminAttReportRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminClassSheetRoute: typeof AdminClassSheetRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminParentsRoute: typeof AdminParentsRoute
  AdminParentsInvitedRoute: typeof AdminParentsInvitedRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminResultQueueRoute: typeof AdminResultQueueRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpendingsRoute: typeof AdminSpendingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStaffAdminRoute: typeof AdminStaffAdminRoute
  AdminStaffOtherRoute: typeof AdminStaffOtherRoute
  AdminStaffTeachersRoute: typeof AdminStaffTeachersRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminTermsRoute: typeof AdminTermsRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionActionRoute: typeof AdminCollectionActionRoute
  AdminCollectionNewRoute: typeof AdminCollectionNewRoute
  AdminCollectPupilRoute: typeof AdminCollectPupilRoute
  AdminCollectReportRoute: typeof AdminCollectReportRoute
  AdminCollectIndexRoute: typeof AdminCollectIndexRoute
  AdminCollectionRecordIdEditRoute: typeof AdminCollectionRecordIdEditRoute
  AdminCollectReceiptInvoiceIdRoute: typeof AdminCollectReceiptInvoiceIdRoute
  AdminCollectionRecordIdIndexRoute: typeof AdminCollectionRecordIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicantsRoute: AdminApplicantsRoute,
  AdminArmsRoute: AdminArmsRoute,
  AdminAttReportRoute: AdminAttReportRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminClassSheetRoute: AdminClassSheetRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminParentsRoute: AdminParentsRoute,
  AdminParentsInvitedRoute: AdminParentsInvitedRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminResultQueueRoute: AdminResultQueueRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpendingsRoute: AdminSpendingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStaffAdminRoute: AdminStaffAdminRoute,
  AdminStaffOtherRoute: AdminStaffOtherRoute,
  AdminStaffTeachersRoute: AdminStaffTeachersRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminTermsRoute: AdminTermsRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionActionRoute: AdminCollectionActionRoute,
  AdminCollectionNewRoute: AdminCollectionNewRoute,
  AdminCollectPupilRoute: AdminCollectPupilRoute,
  AdminCollectReportRoute: AdminCollectReportRoute,
  AdminCollectIndexRoute: AdminCollectIndexRoute,
  AdminCollectionRecordIdEditRoute: AdminCollectionRecordIdEditRoute,
  AdminCollectReceiptInvoiceIdRoute: AdminCollectReceiptInvoiceIdRoute,
  AdminCollectionRecordIdIndexRoute: AdminCollectionRecordIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ParentRouteRouteChildren {
  ParentAssignmentsRoute: typeof ParentAssignmentsRoute
  ParentAttendanceRoute: typeof ParentAttendanceRoute
  ParentInvoicesRoute: typeof ParentInvoicesRoute
  ParentMsgSchoolRoute: typeof ParentMsgSchoolRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentProfileRoute: typeof ParentProfileRoute
  ParentResultsRoute: typeof ParentResultsRoute
  ParentTimetableRoute: typeof ParentTimetableRoute
  ParentIndexRoute: typeof ParentIndexRoute
  ParentCollectionRecordIdRoute: typeof ParentCollectionRecordIdRoute
  ParentChildrenAddRoute: typeof ParentChildrenAddRoute
  ParentPayDoneRoute: typeof ParentPayDoneRoute
  ParentChildrenIndexRoute: typeof ParentChildrenIndexRoute
  ParentPayIndexRoute: typeof ParentPayIndexRoute
}

const ParentRouteRouteChildren: ParentRouteRouteChildren = {
  ParentAssignmentsRoute: ParentAssignmentsRoute,
  ParentAttendanceRoute: ParentAttendanceRoute,
  ParentInvoicesRoute: ParentInvoicesRoute,
  ParentMsgSchoolRoute: ParentMsgSchoolRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentProfileRoute: ParentProfileRoute,
  ParentResultsRoute: ParentResultsRoute,
  ParentTimetableRoute: ParentTimetableRoute,
  ParentIndexRoute: ParentIndexRoute,
  ParentCollectionRecordIdRoute: ParentCollectionRecordIdRoute,
  ParentChildrenAddRoute: ParentChildrenAddRoute,
  ParentPayDoneRoute: ParentPayDoneRoute,
  ParentChildrenIndexRoute: ParentChildrenIndexRoute,
  ParentPayIndexRoute: ParentPayIndexRoute,
}

const ParentRouteRouteWithChildren = ParentRouteRoute._addFileChildren(
  ParentRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentInvoicesRoute: typeof StudentInvoicesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCollectionRecordIdRoute: typeof StudentCollectionRecordIdRoute
  StudentAssignmentsIndexRoute: typeof StudentAssignmentsIndexRoute
  StudentMaterialsIndexRoute: typeof StudentMaterialsIndexRoute
  StudentAssignmentsAssignmentIdResultRoute: typeof StudentAssignmentsAssignmentIdResultRoute
  StudentAssignmentsAssignmentIdIndexRoute: typeof StudentAssignmentsAssignmentIdIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentInvoicesRoute: StudentInvoicesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCollectionRecordIdRoute: StudentCollectionRecordIdRoute,
  StudentAssignmentsIndexRoute: StudentAssignmentsIndexRoute,
  StudentMaterialsIndexRoute: StudentMaterialsIndexRoute,
  StudentAssignmentsAssignmentIdResultRoute:
    StudentAssignmentsAssignmentIdResultRoute,
  StudentAssignmentsAssignmentIdIndexRoute:
    StudentAssignmentsAssignmentIdIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface TeacherRouteRouteChildren {
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherEclassesRoute: typeof TeacherEclassesRoute
  TeacherMsgAdminRoute: typeof TeacherMsgAdminRoute
  TeacherMsgStudentsRoute: typeof TeacherMsgStudentsRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherQuestionsRoute: typeof TeacherQuestionsRoute
  TeacherRegistersRoute: typeof TeacherRegistersRoute
  TeacherResultsRoute: typeof TeacherResultsRoute
  TeacherScoresRoute: typeof TeacherScoresRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherSubjectsRoute: typeof TeacherSubjectsRoute
  TeacherSubmissionsRoute: typeof TeacherSubmissionsRoute
  TeacherTimetableRoute: typeof TeacherTimetableRoute
  TeacherTopicsRoute: typeof TeacherTopicsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherCollectionNewRoute: typeof TeacherCollectionNewRoute
  TeacherUploadsIndexRoute: typeof TeacherUploadsIndexRoute
  TeacherCollectionRecordIdEditRoute: typeof TeacherCollectionRecordIdEditRoute
  TeacherCollectionRecordIdIndexRoute: typeof TeacherCollectionRecordIdIndexRoute
}

const TeacherRouteRouteChildren: TeacherRouteRouteChildren = {
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherEclassesRoute: TeacherEclassesRoute,
  TeacherMsgAdminRoute: TeacherMsgAdminRoute,
  TeacherMsgStudentsRoute: TeacherMsgStudentsRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherQuestionsRoute: TeacherQuestionsRoute,
  TeacherRegistersRoute: TeacherRegistersRoute,
  TeacherResultsRoute: TeacherResultsRoute,
  TeacherScoresRoute: TeacherScoresRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherSubjectsRoute: TeacherSubjectsRoute,
  TeacherSubmissionsRoute: TeacherSubmissionsRoute,
  TeacherTimetableRoute: TeacherTimetableRoute,
  TeacherTopicsRoute: TeacherTopicsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherCollectionNewRoute: TeacherCollectionNewRoute,
  TeacherUploadsIndexRoute: TeacherUploadsIndexRoute,
  TeacherCollectionRecordIdEditRoute: TeacherCollectionRecordIdEditRoute,
  TeacherCollectionRecordIdIndexRoute: TeacherCollectionRecordIdIndexRoute,
}

const TeacherRouteRouteWithChildren = TeacherRouteRoute._addFileChildren(
  TeacherRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthFirstSignInRoute: typeof AuthFirstSignInRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSessionExpiredRoute: typeof AuthSessionExpiredRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignedInRoute: typeof AuthSignedInRoute
  AuthWrongPortalRoute: typeof AuthWrongPortalRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthFirstSignInRoute: AuthFirstSignInRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSessionExpiredRoute: AuthSessionExpiredRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignedInRoute: AuthSignedInRoute,
  AuthWrongPortalRoute: AuthWrongPortalRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ParentRouteRoute: ParentRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  TeacherRouteRoute: TeacherRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
